test

diff --git a/INO/GCL1/NBS411634/commit-msg b/INO/GCL1/NBS411634/commit-msg
--- a/INO/GCL1/NBS411634/commit-msg
+++ b/INO/GCL1/NBS411634/commit-msg
@@ -1,10 +1,9 @@
 !/bin/sh
 
-COMMIT_MSG_FILE=$1
 
 #Skrypt weryfikujacy, czy kazdy "commit message" zaczyna sie od "NBS411634"
 
-if ! grep -q '^NBS411634' "$COMMIT_MSG_FILE"; then
-	echo >&2 "ERROR! Commit message nie rozpoczyna sie od: 'NBS411634'! "
+if ! grep -q '^NBS411634' "$1"; then
+	echo "ERROR! Commit message nie rozpoczyna sie od: 'NBS411634'! "
 	exit 1
 fi
